// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89....
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

fn main() {
    let mut sum = 0;
    let (mut a, mut b) = (1, 2); // First two terms of Fibonacci sequence
    while b <= 4000000 {
        if b % 2 == 0 {
            sum += b;
        }
        let next = a + b;
        a = b;
        b = next;
    }
    println!("Sum of even-valued terms in Fibonacci sequence: {}", sum);

}
